services:
  core:
    ports:
      - "8000:8000"
    env_file:
      - ./core/.env
    build:
      context: ./core
      dockerfile: ./Dockerfile.dev
    develop:
      watch:
        - action: rebuild
          path: ./core

    # depends_on:
    #   db:
    #     condition: service_healthy
    #     restart: true
      # redis:
        # condition: service_started

  # db:
  #   image: postgres
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  #     interval: 10s
  #     retries: 5
  #     start_period: 30s
  #     timeout: 10s

  #ui:
    #
  
  # reverse_proxy:
    #
